import { createClient } from "npm:@supabase/supabase-js@2";
type Row={criterion_key?:string;title?:string;description?:string;scale_1?:string;scale_2?:string;scale_3?:string;scale_4?:string;scale_5?:string;sort_order?:string};
const h={"Access-Control-Allow-Origin":"https://jinnat-lht.github.io","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...h,"Content-Type":"application/json"}});
const clean=(v:unknown)=>String(v??"").trim();
Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:h});if(req.method!=="POST")return out({error:"Method not allowed"},405);
 const token=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,""),url=Deno.env.get("SUPABASE_URL")??"",anon=Deno.env.get("SUPABASE_ANON_KEY")??Deno.env.get("SUPABASE_PUBLISHABLE_KEY")??"",secret=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??Deno.env.get("SUPABASE_SECRET_KEY")??"";
 if(!token||!url||!anon||!secret)return out({error:"Authentication or configuration missing"},401);
 const uc=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data:{user}}=await uc.auth.getUser(token);if(!user)return out({error:"Invalid session"},401);
 const db=createClient(url,secret,{auth:{persistSession:false}});const {data:account}=await db.from("user_accounts").select("id,account_type,status").eq("id",user.id).maybeSingle();if(!account||account.account_type!=="ADMIN"||account.status!=="ACTIVE")return out({error:"Admin access required"},403);
 const p=await req.json().catch(()=>({})),action=clean(p.action||"validate").toLowerCase(),batchCode=clean(p.batch_code),rows:Array<Row>=Array.isArray(p.rows)?p.rows:[];
 if(!batchCode||!rows.length)return out({error:"batch_code and rows are required"},400);if(rows.length>100)return out({error:"Maximum 100 criteria per import"},400);
 const {data:batch}=await db.from("batches").select("id,program_id").eq("external_code",batchCode).is("deleted_at",null).maybeSingle();if(!batch)return out({error:"Batch not found"},404);
 const {data:program}=await db.from("programs").select("id,client_organization_id,current_version_id").eq("id",batch.program_id).maybeSingle();if(!program?.current_version_id)return out({error:"Program has no current version"},422);
 const errors:any[]=[];const valid=rows.map((r,i)=>{const x={criterion_key:clean(r.criterion_key).toUpperCase(),title:clean(r.title),description:clean(r.description),scale_labels:{1:clean(r.scale_1),2:clean(r.scale_2),3:clean(r.scale_3),4:clean(r.scale_4),5:clean(r.scale_5)},sort_order:Number(r.sort_order)||i+1};const n=i+2;if(!/^[A-Z0-9_]+$/.test(x.criterion_key))errors.push({row:n,field:"criterion_key",message:"Use uppercase letters, numbers, and underscores"});if(!x.title)errors.push({row:n,field:"title",message:"Title is required"});for(const k of Object.keys(x.scale_labels))if(!x.scale_labels[k as keyof typeof x.scale_labels])errors.push({row:n,field:"scale_"+k,message:"Scale label is required"});return x;});
 if(new Set(valid.map(x=>x.criterion_key)).size!==valid.length)errors.push({row:0,field:"criterion_key",message:"criterion_key must be unique"});
 if(action==="validate")return out({valid:!errors.length,total_rows:rows.length,valid_rows:errors.length?0:valid.length,errors});if(action!=="commit")return out({error:"Unsupported action"},400);if(errors.length)return out({error:"Fix validation errors before confirming",errors},422);
 const {data:job,error:jobError}=await db.from("import_jobs").insert({import_type:"BEHAVIOR_CRITERIA",status:"CONFIRMED",client_organization_id:program.client_organization_id,program_id:program.id,batch_id:batch.id,source_filename:"browser-self-assessment-import",template_version:"1.0",uploaded_by:user.id,total_rows:valid.length,valid_rows:valid.length}).select("id").single();if(jobError||!job)return out({error:"Unable to create import audit record"},500);
 try{const criterionVersionIds=[];for(const x of valid){let {data:criterion}=await db.from("behavior_criteria").select("id").eq("program_id",program.id).eq("criterion_key",x.criterion_key).is("deleted_at",null).maybeSingle();if(!criterion){const q=await db.from("behavior_criteria").insert({program_id:program.id,criterion_key:x.criterion_key}).select("id").single();if(q.error||!q.data)throw new Error("Could not create "+x.criterion_key);criterion=q.data;}const v=await db.from("behavior_criterion_versions").insert({behavior_criterion_id:criterion.id,program_version_id:program.current_version_id,title:x.title,description:x.description||null,scale_labels:x.scale_labels}).select("id").single();if(v.error||!v.data)throw new Error("Could not save "+x.criterion_key);criterionVersionIds.push(v.data.id);}await db.from("batch_content_snapshots").update({snapshot_json:{criterion_version_ids:criterionVersionIds}}).eq("batch_id",batch.id);await db.from("import_jobs").update({status:"COMMITTED",committed_at:new Date().toISOString()}).eq("id",job.id);return out({committed:true,imported_count:valid.length});}catch(e){await db.from("import_jobs").update({status:"FAILED"}).eq("id",job.id);return out({error:e instanceof Error?e.message:"Import failed"},400);}
});