import { createClient } from "npm:@supabase/supabase-js@2";
const ORIGIN="https://jinnat-lht.github.io";
const headers={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...headers,"Content-Type":"application/json"}});
async function rolesFor(db:any,userId:string){const a=await db.from("user_accounts").select("account_type,status").eq("id",userId).maybeSingle();if(!a.data||a.data.account_type!=="ADMIN"||a.data.status!=="ACTIVE")return null;const r=await db.from("role_assignments").select("scope_type,provider_organization_id,client_organization_id,program_id,batch_id").eq("user_id",userId).eq("role","ADMIN").is("revoked_at",null);return r.data??[];}
async function canManage(db:any,roles:any[],batchId:string){const b=await db.from("batches").select("id,program_id").eq("id",batchId).maybeSingle();if(!b.data)return false;const p=await db.from("programs").select("id,client_organization_id").eq("id",b.data.program_id).maybeSingle();if(!p.data)return false;const c=await db.from("client_organizations").select("id,provider_organization_id").eq("id",p.data.client_organization_id).maybeSingle();if(!c.data)return false;return roles.some(r=>(r.scope_type==="PROVIDER"&&r.provider_organization_id===c.data.provider_organization_id)||(r.scope_type==="CLIENT_ORGANIZATION"&&r.client_organization_id===c.data.id)||(r.scope_type==="PROGRAM"&&r.program_id===p.data.id)||(r.scope_type==="BATCH"&&r.batch_id===b.data.id));}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers});const token=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,""),url=Deno.env.get("SUPABASE_URL")??"",anon=Deno.env.get("SUPABASE_ANON_KEY")??Deno.env.get("SUPABASE_PUBLISHABLE_KEY")??"",secret=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??Deno.env.get("SUPABASE_SECRET_KEY")??"";if(!token||!url||!anon||!secret)return out({error:"Authentication or configuration missing"},401);const client=createClient(url,anon,{global:{headers:{Authorization:"Bearer "+token}},auth:{persistSession:false}}),user=(await client.auth.getUser(token)).data.user;if(!user)return out({error:"Invalid session"},401);const db=createClient(url,secret,{auth:{persistSession:false}}),payload=await req.json().catch(()=>({})),batchId=String(payload.batch_id??""),roles=await rolesFor(db,user.id);if(!roles||!batchId||!(await canManage(db,roles,batchId)))return out({error:"Administrator access to this batch is required"},403);
const configs=await db.from("batch_activity_configs").select("activity_type,config_json").eq("batch_id",batchId).in("activity_type",["SELF_BEFORE","SELF_AFTER"]);if(configs.error)return out({error:"Could not load activity configuration"},500);const reference=(configs.data??[]).find((c:any)=>Array.isArray(c.config_json?.criteria)&&c.config_json.criteria.length===5);const criteria=reference?.config_json?.criteria??[];if(criteria.length!==5)return out({error:"ยังไม่ได้ตั้งค่าเกณฑ์ Self-assessment สำหรับ Batch นี้"},422);
const subs=await db.from("submissions").select("batch_learner_id,activity_type,status,submission_attempts(response_json,attempt_number)").eq("batch_id",batchId).in("activity_type",["SELF_BEFORE","SELF_AFTER"]).in("status",["SUBMITTED","PASSED","REVIEWED"]);if(subs.error)return out({error:"Could not load submissions"},500);const values:any={SELF_BEFORE:{},SELF_AFTER:{}};for(const row of subs.data??[]){const attempt=[...(row.submission_attempts??[])].sort((a:any,b:any)=>Number(b.attempt_number)-Number(a.attempt_number))[0],ratings=attempt?.response_json?.ratings;if(!ratings)continue;for(const criterion of criteria){const value=Number(ratings[criterion.key]);if(value>=1&&value<=5){const list=values[row.activity_type][criterion.key]??[];list.push(value);values[row.activity_type][criterion.key]=list;}}}
const average=(list:number[])=>list?.length?Number((list.reduce((a,b)=>a+b,0)/list.length).toFixed(2)):null;const rows=criteria.map((c:any)=>{const before=average(values.SELF_BEFORE[c.key]),after=average(values.SELF_AFTER[c.key]);return {key:c.key,title:c.title,before,after,difference:before!=null&&after!=null?Number((after-before).toFixed(2)):null,before_count:(values.SELF_BEFORE[c.key]??[]).length,after_count:(values.SELF_AFTER[c.key]??[]).length};});return out({criteria:criteria.map((c:any)=>({key:c.key,title:c.title,description:c.description})),rows,before_respondents:new Set((subs.data??[]).filter((s:any)=>s.activity_type==="SELF_BEFORE").map((s:any)=>s.batch_learner_id)).size,after_respondents:new Set((subs.data??[]).filter((s:any)=>s.activity_type==="SELF_AFTER").map((s:any)=>s.batch_learner_id)).size});});